name: Build protoc-zig

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  PROTOBUF_VER: 3.21.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup zig
      run: |
        sudo snap install zig --classic --beta
        zig version

    # https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md
    - name: Install Protobuf
      run: |
        URL="https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-${PROTOBUF_VER}.tar.gz"
        echo "downloading from: ${URL}"
        wget -qO- $URL | tar xvz
        cd protobuf-$PROTOBUF_VER
        CXX="zig c++" CC="zig cc" cmake . 
        cmake --build . --parallel 10
        sudo cmake --install .
 
    - name: Configure CMake
      run: |
        cd ${{github.workspace}}/protoc-zig
        mkdir build
        pushd build
        CXX="zig c++" CC="zig cc" cmake ..

    - name: Build
      run: |
        make


