name: Build protoc-zig

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  PROTOBUF_URL: https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Protobuf
      run: |
        wget -qO- $PROTOBUF_URL | tar xvz
        ls 
    
    - name: Setup zig
      run: |
        sudo snap install zig --classic --beta
        zig version

    - name: Configure CMake
      run: |
        cd ${{github.workspace}}/protoc-zig
        mkdir build
        pushd build
        CXX="zig c++" CC="zig cc" cmake ..

    - name: Build
      run: |
        make


